// Code generated by "stringer -type TokenType -trimprefix Token"; DO NOT EDIT.

package tplexpr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenValue-0]
	_ = x[TokenIdent-1]
	_ = x[TokenLeftParen-2]
	_ = x[TokenRightParen-3]
	_ = x[TokenDot-4]
	_ = x[TokenComma-5]
	_ = x[TokenEOF-6]
	_ = x[TokenString-7]
	_ = x[TokenArrow-8]
	_ = x[TokenDeclare-9]
	_ = x[TokenGT-10]
	_ = x[TokenGE-11]
	_ = x[TokenEQ-12]
	_ = x[TokenNE-13]
	_ = x[TokenLE-14]
	_ = x[TokenLT-15]
	_ = x[TokenAND-16]
	_ = x[TokenOR-17]
	_ = x[TokenError-18]
}

const _TokenType_name = "ValueIdentLeftParenRightParenDotCommaEOFStringArrowDeclareGTGEEQNELELTANDORError"

var _TokenType_index = [...]uint8{0, 5, 10, 19, 29, 32, 37, 40, 46, 51, 58, 60, 62, 64, 66, 68, 70, 73, 75, 80}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
